### ISSUE TITLE
"tar" vulnerability

### ISSUE THREAD

**Issue by rbest** [js-advancers/gutenberg-react-on-the-frontend-practice#1]
@fabiankaegy heads up. Did you receive the 'tar' security alert from GitHub? How would you like us/me to deal with this? Any specifics before moving forward.

**Comment by fabiankaegy** [comment]
@rbest I just saw it as well, and digged around a but. Looks like it is coming from `node-sass > node-gyp > tar` which means that because it is only running on the dev process we should be fine to wait for the fix in the node-sass issue referenced below. 

https://github.com/sass/node-sass/issues/2625

What do you think?

**Comment by rbest** [comment]
Agreed! Thanks for checking. I’ll keep an eye out for any updates over the next couple of days. You do the same. If I learn thing new during daylight hours 😉 I’ll ping you direct in Slack. 

Rita Best
